repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        exclude: (?x).png
  - repo: local
    hooks:
      - id: yew-fmt
        name: yew-fmt
        entry: yew-fmt
        language: system
        types:
          - rust
      - id: tombi-format
        name: tombi format
        entry: mise exec -- tombi format
        language: system
        types:
          - toml
      - id: tombi-lint
        name: tombi lint
        entry: mise exec -- tombi lint
        language: system
        types:
          - toml
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor
        pass_filenames: false
        args:
          - '--no-progress' # https://github.com/zizmorcore/zizmor/issues/582
          - '.github'
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args:
          - '--all-targets'
          - '--all-features'
          - '--'
          - '-D'
          - 'warnings'
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
